### ISSUE TITLE
Continuous integration?

### ISSUE THREAD

**Issue by tyleo** [runem/ts-simple-type#12]
How do you feel about continuous integration? I may iterate on ts-simple-type a bit and would like to have the security of knowing that my changes will pass on more platforms.

I've set up one of my own GitHub projects with AppVeyor and TravisCI in the past. I could take those steps if you would like or try to integrate a different service.

**Comment by runem** [comment]
Great idea! Now that we are two people working on this project I definitely think we should set it up.

I've had success using CircleCI in the past, so have set it up with PR https://github.com/runem/ts-simple-type/pull/14. CircleCI now runs for every commit and PR :+1:
