### ISSUE TITLE
Support `"incremental": true` in tsconfig.json

### ISSUE THREAD

**Issue by tyleo** [runem/ts-simple-type#13]
`"incremental": true` greatly decreases compile times for typescript projects. Sometimes as much as 10x.

Usually it's as simple as adding `"incremental": true` in tsconfig.json but many of the scripts for ts-simple-type `rm -rf` before running additional operations. The `incremental` flag stores some information alongside generated .js files which allows parts of compilation to be skipped in additional runs of `tsc`.

I propose changing some of the scripts so that they can take advantage of this flag. Right now there are:
```
"test": "rm -rf dist & tsc && ava dist/test/**/*.spec.js -- $LINE",
"test:watch": "rm -rf dist && tsc --watch & ava dist/test/**/*.spec.js --watch",
"watch": "rm -rf lib && rollup -c --watch",
"build": "rm -rf lib && rollup -c"
```

I'd suggest something like:
```
"prepare": "npm run rebuild:prod",
"test: tsc && ava dist/test/**/*.spec.js --$LINE",
"test:watch": tsc --watch & ava dist/test/**/*.spec.js --watch",
"build": "tsc"
"build:watch": "tsc --watch",
"build:prod": "rollup -c"
"build:prod:watch": "rollup -c --watch",
"rebuild": "rm -rf dist && tsc",
"rebuild:watch": "rm -rf dist && tsc --watch",
"rebuild:prod": "rm -rf lib && rollup -c",
"rebuild:prod:watch": "rm -rf lib && rollup -c --watch",
"rebuild:test": "rm -rf dist & tsc && ava dist/test/**/*.spec.js -- $LINE",
"rebuild:test:watch": "rm -rf dist && tsc --watch & ava dist/test/**/*.spec.js --watch"
```

or, alternatively:
```
"prepare": "npm run clean & npm run build:prod",
"clean": "rm -rf lib & rm -rf dist",
"test": "tsc && ava dist/test/**/*.spec.js --$LINE",
"test:watch": tsc --watch & ava dist/test/**/*.spec.js --watch",
"build": "tsc"
"build:watch": "tsc --watch",
"build:prod": "rollup -c"
"build:prod:watch": "rollup -c --watch",
```

This way the standard commands could take advantage of incremental compilation and production builds would no longer be the default. My main requirement is just to have an option for a non-production build which doesn't delete build artifacts. I could get by with just adding `"build:dev": "tsc"`. If I'm already making changes I'd like to get your thoughts on the additional commands though.

**Comment by runem** [comment]
Thanks for your suggestion! I have now implemented support for incremental builds as well as non-production builds which doesn't delete build artifacts :tada:
