### ISSUE TITLE
SimpleTypeCircularRef is misspelled "SimpleTyoeCircularRef"

### ISSUE THREAD

**Issue by tyleo** [runem/ts-simple-type#7]
Here is the offending line:

https://github.com/runem/ts-simple-type/blob/d881940eab8161e89553bb892abac2e678694812/src/simple-type.ts#L228

**Comment by tyleo** [comment]
I was hoping to fix this myself but couldn't make progress due to #6.

**Comment by runem** [comment]
Great catch! :blush: 

I have fixed it now, and will publish a new version during this week. Thanks for opening an issue!
